---
plugins:
   - "@semantic-release/commit-analyzer"
   - "@semantic-release/release-notes-generator"
   - "@semantic-release/github"

preset: eslint
success: false
fail: false
npmPublish: false
tarballDir: false
tagFormat: "${version}"